#' Censor a specified data.table at specific row_ids.
#'
#' This function changes the values at `[hcc, row_id]` for each of the row_ids
#' from 0 or 1 to 0 in place.
#'
#' @param curr_dt (data.table) The data.table to upcode. This is a binary data.table with
#' rows corresponding to people and columns corresponding to 115 HCCs (from v28 of CMS-HCC) and one column for
#'   person_ids. If it has not been modified already, this is generated by simulate_baseline_v28_data
#' @param all_censoring_row_id_tbl (tibble) All row ids to right censor across all time points
#' @param t (int) The current time point, must be greater than or equal to 1
#'
#' @export
censor_by_row_ids <- function(curr_dt, all_censoring_row_id_tbl, t) {
  # Get relevant row ids to censor
  row_ids_to_censor <- all_censoring_row_id_tbl |>
    dplyr::filter(timepoint == t) |>
    tidyr::unnest(row_ids) |>
    dplyr::pull(row_ids)

  # Censor specified row ids
  data.table::set(curr_dt, row_ids_to_censor, v28_hccs, value = 0)
}
