# This file contains two functions: check_curr_dt and format_as_data_table, which is a
# helper for check_curr_dt. At a high level, check_curr_dt verifies if the input
# provides is a data.table with the expected columns (person_id and the version 28 HCCs
# from the CMS-HCC risk adjustment formula). format_as_data_table helps with this by
# trying to cast the input as a data.table and throwing an error message if that doesn't work.

#' Verifies whether curr.dt is a data.table and has the expected columns. Expected columns
#' should be "person_id" followed by the HCCs in version 28 of the CMS-HCC risk adjustment formula.
#' As a note, you can access these HCCs with `v28_hccs` (they are a global variable in this package).
#'
#' @param curr_dt (data.table) The data.table to verify. This should be a binary data.table with
#' rows corresponding to people and columns corresponding to 115 HCCs (from v28 of CMS-HCC) and one column for
#'   person_ids. If it has not been modified already, this is generated by simulate_baseline_v28_data
#'
#' @export
check_curr_dt <- function(curr_dt) {
  # Try to format as a data.table
  format_as_data_table(curr_dt)

  # set column names to lower case
  names(curr_dt) <- tolower(names(curr_dt))

  # check curr_dt contains all v28 HCCs
  if (
    length(colnames(curr_dt)) != 116 |
      length(intersect(
        colnames(curr_dt),
        c("person_id", v28_hccs)
      )) !=
        116
  ) {
    stop(
      "Column names should be the v28 HCCs and one 'person_id' column only. You can find the v28 hccs by typing `v28_hccs` in the console when this package is loaded. There should be 115 hccs total, and they should be labeled in lower case (e.g. 'hcc1')"
    )
  }
}

#' @importFrom data.table setDT
format_as_data_table <- function(x) {
  tryCatch(
    expr = {
      data.table::setDT(x)
    },
    error = function(e) {
      stop("curr_dt must be a data.table or able to be cast as a data.table")
      print(e)
    }
  )
}
