#' Upcode a specified data.table at specific row_ids.
#'
#' This function changes the values at `[hcc, row_id]` for each of the row_ids
#' from 0 to 1 in place.
#'
#'
#' @param curr_dt (data.table; also accepts data.frame or tibble) The data.table to upcode. This is a binary data.table with
#' rows corresponding to people and columns corresponding to 115 HCCs (from v28 of CMS-HCC) and one column for
#'   person_ids. If it has not been modified already, this is generated by simulate_baseline_v28_data
#' @param all_upcoding_row_id_tbl (tibble) Tibble of all row ids upcode across all time points
#' @param h (int) the hcc (e.g. column) to upcode
#' @param t (int) the specified time point
#'
#' @export
upcode_hcc_by_row_ids <- function(curr_dt, all_upcoding_row_id_tbl, h, t) {
  # Cast to data.table
  data.table::setDT(curr_dt)

  # Get relevant row IDs to upcode
  row_ids_to_upcode <- all_upcoding_row_id_tbl |>
    dplyr::filter(hcc == h & timepoint == t) |>
    tidyr::unnest(row_ids) |>
    dplyr::pull(row_ids)

  # Upcode specified row ids
  if (length(row_ids_to_upcode) > 0) {
    data.table::set(curr_dt, row_ids_to_upcode, c(h), value = 1)
  }
}
